# Main Workflow for Building & Publishing Github Containers to ghcr.io
name: Docker Build & Publish to GitHub Container Registry
on:
  push:
    tags:
      - 'main'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Get bitnami tag
        run: . /images/pgvecto-bitnami/bitnami-tag.sh

      - name: Build and Push Versioned Docker Image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.BITNAMI_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BITNAMI_TAG=${{ env.BITNAMI_TAG }}